version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '16379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - .cache/redis:/data
